
image:
  file: .gitpod.dockerfile

ports:
  - port: 8080
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
  - port: 8025
    onOpen: ignore
  - port: 1025
    onOpen: ignore
  - port: 9000
    onOpen: ignore
  
tasks:
  - name: Some init
    command: |
      sudo service mysql start
      sudo service php8.1-fpm start
      sudo service nginx start
      sudo mailhog </dev/null &>/dev/null & disown
      /bin/bash .init.sh
