
image:
  file: .gitpod.dockerfile

ports:
  - port: 8080
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
  - port: 8025
    onOpen: ignore
  - port: 1025
    onOpen: ignore
  - port: 9000
    onOpen: ignore

tasks:
  - init: mysql start # or wp-setup-theme
    command: php8.1-fom start
  
  # start MailHog (SMTP testing tool) 
  - command: mailhogs

  - command: nginx start